### ISSUE TITLE
Please take down this repository of copied code.

### ISSUE THREAD

**Issue by JohnB17** [CorwinDev/Nextcloud#1]
Hello Corwin. I would like to talk to you about https://pterodactylmarket.com/resource/507 and this repository because they are obviously copied from our https://pterodactylmarket.com/resource/311 and https://github.com/finnie2006/ptero-eggs (Nextcloud branches). I would like you to please take that down on both your Github and Pterodactyl Market page. If you do not within 48 hours I will be filing a DMCA request with Github and a request to Pterodactyl Market.

**Comment by CorwinDev** [comment]
Hi, I haven't copied it, as you see in the code its definitly difference.

**Comment by finnie2006** [comment]
No its not

**Comment by CorwinDev** [comment]
Look at the commits

**Comment by JohnB17** [comment]
All you did was reformat the spacing in the Dockerfile, removed a few packages, and changed the php version from 8.1 to 7. That is not different. You can't make a three very small changes and call it a new product.

**Comment by CorwinDev** [comment]
And btw yours isn't working 😂

**Comment by CorwinDev** [comment]
Can you maybe send your discord? It's maybe easyer

**Comment by PurpleCube** [comment]
Corwin, I do not know these people but saw the resource you published on PterodactylMarket. I would like you to take it down as you are clearly breaking someone's terms of service and taking credit for something someone else spent their time on. The makers of this resource have the right to tell you to remove this resource and take it down.

**Comment by CorwinDev** [comment]
I’ve permission from the owners to develop on it
